wandb:
  wb_tracking: true
  wb_project_name:  'ACID' # if 'wb_tracking'=True, The name of the W&B project to associate the run with. Default is 'SmartVille'
  wb_run_name: 'DDQN'

neural_modules:
  hidden_size: 200

intrusion_detection:
  agent: DDQN
  flowstats_freq_secs: 1
  bad_classif_penalisation: hard
  use_transition_model: true
  max_budget: 300
  min_budget: -60
  useless_epistemic_penalty: 7
  epistemic_is_blocking: false
  hard_bad_classif_cost_factor: 8
  greedy_update: true
  # epistemic_regularisation_factor: 0.05
  # entropy_reg_coefficient: 0
  # surrogate_policy_consistency: true
  # use_critic_to_act: false
  # variational_tmodel: true


base_params: 
  disable_proxy: true
  replay_speed: 20 # Replay speed factor
