
health_monitoring: true

wandb:
  wb_run_name: 'PT_H200_noenc_distkr_R1_blazingfast'

neural_modules:
  hidden_size: 200

  
intrusion_detection:
  pretrained_inference: false
  epistemic_agency: false
  online_evaluation: true
  report_step_freq: 10
  inference_freq_secs: 1
  flowstats_freq_secs: 6

  
topology_creator:
  contr_start: sh
  use_gns3_config_file: false
  ADDITIONAL_ENV_VARS: |
    https_proxy=http://proxy.uninsubria.it:3128
    HTTPS_PROXY=http://proxy.uninsubria.it:3128
    HTTP_PROXY=http://proxy.uninsubria.it:3128
    http_proxy=http://proxy.uninsubria.it:3128
    no_proxy=localhost,127.0.0.1
    
base_params: 
  host_ip: 192.168.183.146
  # container_manager_replay_from_file : false
  disable_proxy: true
  replay_speed: 1 # Replay speed factor



honeypots:
  - victim-0:
      pattern: 'doorlock'
      destination: 'victim-1'

  - victim-1:
      pattern: 'doorlock'
      destination: 'victim-0'


attackers:
  - attacker-1:
      pattern: 'cc_heartbeat'
      destination: 'victim-0'

  - attacker-2:
      pattern: 'hakai'
      destination: 'victim-1'

  - benign-1:
      pattern: 'doorlock'
      destination: 'victim-1'  

knowledge:

    bening_patterns: 
        - echo
        - doorlock
        - hue

    attack_patterns:
        - hakai
        - mirai
        - hajime
        - gafgyt
        - muhstik
        - h_scan
        - okiru
        - generic_ddos
        - torii
        - cc_heartbeat

    Knowns:
        - doorlock
        - hakai
        - cc_heartbeat

    G1s:
        - okiru
        - torii
        - generic_ddos 
        

    G2s:
        - mirai
        - gafgyt
        - hajime
        - h_scan
        - muhstik
        - hue
        - echo

