host_ip: 192.168.183.146
disable_proxy: true
node_features: false
inference_models_path: "./models/optim.py"

wandb:
  wb_tracking: true
  wb_run_name: 'rewardscale_10'
  wb_project_name:  'TIGER2.0'
  
intrusion_detection:
  max_budget: 250
  min_budget: -100
  max_episode_steps: 50
  cti_price_factor: 500
  price_decay: true
  bad_classif_cost_factor: 400 # we have a semantic erro in the controller by which we need to scale also this parameter (default is 40).
  useless_epistemic_penalty: 70
  tiger_init_budget: 10
  boltzmann_sampling: false
  agent: DDQN
  wrong_inference_penalisation: easy

neural_modules:
  custom_inference_model_path: true
  custom_classifier_path: multiclass_flow_packet_classifier_pretrained_h200_optim.pt
  custom_confidence_decoder_path: flow_packet_confidence_decoder_pretrained_h200_optim.pt

topology_creator:
  contr_start: sh # COMMENT THIS IF YOU WANT THE TIGER SERVER TO START AUTOMATICALLY
  use_gns3_config_file: false
  ADDITIONAL_ENV_VARS: |
    https_proxy=http://proxy.uninsubria.it:3128
    HTTPS_PROXY=http://proxy.uninsubria.it:3128
    HTTP_PROXY=http://proxy.uninsubria.it:3128
    http_proxy=http://proxy.uninsubria.it:3128
    no_proxy=localhost,127.0.0.1,${topology_creator.controller_ip}
    
rewards:
    - echo: 0.2
    - hakai: -1
    - mirai: -2
    - hajime: -1.3
    - doorlock: 0.5
    - gafgyt: -2.5
    - muhstik: -3.6
    - h_scan: -1.7
    - okiru: -4.8
    - generic_ddos: -2.9
    - torii: -2.1
    - cc_heartbeat: -3.1
    - hue: 0.5
