host_ip: 192.168.183.146
disable_proxy: true
node_features: false
health_monitoring: false

wandb:
  wb_tracking: true
  wb_run_name: 'DDQN'
  wb_project_name:  'TIGER3.0'
  
intrusion_detection:
  boltzmann_sampling: false
  agent: DDQN
  use_neural_KR: false
  ad_loss_backprop_to_encoder: false
  hard_epistemic_action: true
  
topology_creator:
  # contr_start: sh # COMMENT THIS IF YOU WANT THE TIGER SERVER TO START AUTOMATICALLY
  use_gns3_config_file: false
  ADDITIONAL_ENV_VARS: |
    https_proxy=http://proxy.uninsubria.it:3128
    HTTPS_PROXY=http://proxy.uninsubria.it:3128
    HTTP_PROXY=http://proxy.uninsubria.it:3128
    http_proxy=http://proxy.uninsubria.it:3128
    no_proxy=localhost,127.0.0.1,${topology_creator.controller_ip}
    

