health_monitoring: true
use_packet_feats: false


wandb:
 wb_tracking: true
 wb_run_name: 'PT'
 wb_project_name:  'TIGER2.0'
 plots: true

neural_modules:
  hidden_size: 200
  dropout: 0.2


intrusion_detection:
  pretrained_inference: false
  epistemic_agency: false
  online_evaluation: true
  save_models: true
  report_step_freq: 10
  resample_packets : false # baseline, for overhead comparisons.
  
topology_creator:
  use_gns3_config_file: false
  ADDITIONAL_ENV_VARS: |
    https_proxy=http://proxy.uninsubria.it:3128
    HTTPS_PROXY=http://proxy.uninsubria.it:3128
    HTTP_PROXY=http://proxy.uninsubria.it:3128
    http_proxy=http://proxy.uninsubria.it:3128
    no_proxy=localhost,127.0.0.1,${topology_creator.controller_ip}
    
base_params: 
  host_ip: 192.168.183.146
  # container_manager_replay_from_file : false
  disable_proxy: true