host_ip: 192.168.183.146
disable_proxy: true

wandb:
  wb_tracking: true
  wb_run_name: 'DDQN'
  wb_project_name:  'TIGER2.0'

neural_modules:
  hidden_size: 200
  
intrusion_detection:
  boltzmann_sampling: false
  agent: DDQN
  bad_classif_penalisation: hard
  use_transition_model: true
  max_budget: 300
  min_budget: -60
  useless_epistemic_penalty: 7
  epistemic_is_blocking: false
  hard_bad_classif_cost_factor: 8
  greedy_update: true
  # epistemic_regularisation_factor: 0.05
  # entropy_reg_coefficient: 0
  # surrogate_policy_consistency: true
  # use_critic_to_act: false
  # variational_tmodel: true

topology_creator:
  contr_start: sh # COMMENT THIS IF YOU WANT POX TO START AUTOMATICALLY
  # victim_start: sh # COMMENT THIS IF YOU WANT TO START THE VICTIM SERVER AUTOMATICALLY
  use_gns3_config_file: false
  ADDITIONAL_ENV_VARS: |
    https_proxy=http://proxy.uninsubria.it:3128
    HTTPS_PROXY=http://proxy.uninsubria.it:3128
    HTTP_PROXY=http://proxy.uninsubria.it:3128
    http_proxy=http://proxy.uninsubria.it:3128
    no_proxy=localhost,127.0.0.1,${topology_creator.controller_ip}
    
