host_ip: 192.168.183.146
disable_proxy: true
node_features: false

wandb:
  wb_tracking: true
  wb_run_name: 'DDQN'
  wb_project_name:  'TIGER2.0'
  
intrusion_detection:
  max_budget: 25
  min_budget: -10
  max_episode_steps: 50
  cti_price_factor: 50
  price_decay: true
  boltzmann_sampling: false
  agent: DDQN
  wrong_inference_penalisation: easy


topology_creator:
  contr_start: sh # COMMENT THIS IF YOU WANT THE TIGER SERVER TO START AUTOMATICALLY
  use_gns3_config_file: false
  ADDITIONAL_ENV_VARS: |
    https_proxy=http://proxy.uninsubria.it:3128
    HTTPS_PROXY=http://proxy.uninsubria.it:3128
    HTTP_PROXY=http://proxy.uninsubria.it:3128
    http_proxy=http://proxy.uninsubria.it:3128
    no_proxy=localhost,127.0.0.1,${topology_creator.controller_ip}