intrusion_detection:
  wb_tracking: true
  wb_project_name:  'ACID' # if 'wb_tracking'=True, The name of the W&B project to associate the run with. Default is 'SmartVille'
  wb_run_name: 'DAIDT'
  agent: DAI
  h_dim: 200
  inference_freq_secs: 0.5
  flowstats_freq_secs: 1
  bad_classif_penalisation: hard
  use_transition_model: true
  max_budget: 300
  min_budget: -60
  useless_epistemic_penalty: 7
  epistemic_is_blocking: false
  hard_bad_classif_cost_factor: 8
  # epistemic_regularisation_factor: 0.05
  # entropy_reg_coefficient: 0
  
topology_creator:
  use_gns3_config_file: false
  env_vars: |
    https_proxy=http://proxy.uninsubria.it:3128
    HTTPS_PROXY=http://proxy.uninsubria.it:3128
    HTTP_PROXY=http://proxy.uninsubria.it:3128
    http_proxy=http://proxy.uninsubria.it:3128
    no_proxy=localhost,127.0.0.1,192.168.122.1
    
base_params: 
  # container_manager_replay_from_file : false
  disable_proxy: true
  replay_speed: 20 # Replay speed factor
