
intrusion_detection:
    use_packet_feats: false

honeypots:
  - victim-0:
      pattern: 'doorlock'
      destination: 'victim-0'
  - victim-1:
      pattern: 'echo'
      destination: 'victim-1'

attackers:
  - attacker-0:
      pattern: 'cc_heartbeat'
      destination: 'victim-0'
  - attacker-1:
      pattern: 'generic_ddos'
      destination: 'victim-1'