
honeypots:
  - victim-0:
      pattern: 'Doorlock'
      destination: 'victim-1'
  - victim-1:
      pattern: 'Echo'
      destination: 'victim-2'

attackers:
  - attacker-0:
      pattern: 'CC_HeartBeat'
      destination: 'victim-0'
  - attacker-1:
      pattern: 'Gen_DDoS'
      destination: 'victim-1'
