override: ""
# SmartVille Configuration

topology_creator:
  # Topology creation configuration
  project: SmartVille

  # Docker images
  controller_docker: pox-controller
  switch_docker: openvswitch
  victim_docker: victim
  attacker_docker: attacker

  # important ips.
  subnet: 192.168.1.0
  netmask: /24
  controller_ip: 192.168.1.1
  main_switch_ip: 192.168.1.2
  bridge_ip: 192.168.1.100
  
  # Controller configuration
  contr_start: "sh"  # Could also be: "./pox.py samples.pretty_log smartController.smartController"

  # GNS3 Configuration
  use_gns3_config_file: true
  gns3_config_path: ~/.config/GNS3/2.2/gns3_server.conf

  # GNS3 Server settings (used when use_gns3_config_file is false)
  gns3_host: localhost
  gns3_port: 3080
  gns3_auth: false
  gns3_username: admin
  gns3_password: admin

  switch_args:
    flow_idle_timeout:  10 # Number of no-activity seconds  for a flow that triggers the switch to delete the corresponding entry in the flow table. Default is 10.
    arp_timeout: 120 # Number of seconds to delete and ARP entry in the switch. Default is 120
    max_buffered_packets: 5  # Max num. of packets the switch buffers while waiting to solve the dest MAC address and forward. Default is 5. 
    max_buffering_secs: 5  # Max time in seconds the switch buffers a packet while waiting to solve the dest MAC address and forward. Default is 5. 
    arp_req_exp_secs: 4 #  Max time in secs. that the switch waits for an ARP response before issuing another requets. (prevents ARP flooding). Default is 4. 
    
  # Environment variables (newline separated)
  env_vars: ''  # Format example: "VAR_ONE=value1\nVAR2=2\nBLABLABLA=something"


base_params:
  # Recommended option is True. (adjust the json file according to your needs) 
  browser_path: '/usr/bin/firefox' # Browser Exetubale Path change to your favourite
  # terminal issuer path:
  # we created a bash script in the utils dir to issue commands on separated pseudo TTYs to keep track
  # of processes' status. If you do not like it, feel free to change it... 
  # make sure to make the terminal_issuer script executable by running  +x terminal_issuer.sh (or whatever other issuer script you create)
  terminal_issuer_path: './terminal_issuer.sh'     
  disable_proxy: false  # Whether to disable the proxy for the nodes of the topology
  dashboard_port: 7777 # Port of the Flask dashboard in the host machine



intrusion_detection:
  eval: false  # Whether to use neural modules in evaluation mode (no training)
  device: 'cpu'  # Can be 'cpu' or 'cuda:0', 'cuda:1', etc. Depending on hw availability
  seed: 777  # A fixed initial seed for random sampling and storing in the experience buffer
  agent: DAI  # can be DQN, DDQN or DAI
  ai_debug: true  # A boolean flag for a verbose version of ML related code
  use_packet_feats: true  # Use first bytes of first packets of each flow alongside flowstats to build feature vectors
  packet_buffer_len: 1  # If 'use_packet_feats'=True, indicates how many packets are retained from each flow to build feature vectors
  packet_feat_dim: 64
  anonymize_transport_ports: true
  flow_feat_dim: 4
  flow_buff_len: 10  # Indicates the flowstats time-window size to build feature vectors
  node_features: false  # Use node features to build the feature vectors
  metric_buffer_len: 10  # If 'node_features'=True, node features time-window size to build feature vectors
  inference_freq_secs: 1  # Time in seconds between two consecutive calls to an inference (and a batch training from experience buffer)
  grafana_user: 'admin'  # Username for the Grafana dashboard (Must coincide with grafana config files, default config files are at usr/share/grafana in the controller)
  grafana_password: 'admin'  # Password for the Grafana dashboard
  max_kafka_conn_retries: 5 #(int, optional): max. num. of connections attempts to the kafka broker. Default is 5.
  curriculum: 1 # labelling scheme for known attacks, train ZdAs and test ZdAs. (can be 0,1, or 2). Default is 1. 
  wb_tracking: false #  Track this run with WeightsAndBiases. (default is False)
  wb_project_name:  'TIGER' # if 'wb_tracking'=True, The name of the W&B project to associate the run with. Default is 'SmartVille'
  wb_run_name: 'My_new_run' # if 'wb_tracking'=True, the name of the W&B run to track training metrics.
  flowstats_freq_secs:  5 # Num. of seconds between two consecutive flowstats request from this controller to its assigned switch. Default is 5.
  dropout: 0.6 # Dropout rate for the neural network. Default is 0.6
  init_k_shot: 4 #  Initial value for k_shot in k_shot learning. Default is 5. 
  batch_size: 16 # Batch size for the neural network. Default is 20
  kernel_regression: True
  report_step_freq: 50 # Frequency of reporting the training step. Default is 50
  use_neural_AD: True
  use_neural_KR: True
  online_evaluation: false
  blocked_benign_cost_factor: 40
  online_evaluation_rounds: 10
  pretrained_inference: True
  h_dim: 800
  max_budget: 25
  max_episode_steps: 750
  min_budget: -10
  multi_class: true  # A boolean flag indicating if the ML classifier should perform multi-class classification
  intelligence_episode_steps: 50
  tiger_init_budget: 1
  cti_price_factor: 4
  replay_batch_size: 32
  pretrained_models_dir: '/pox/pox/smartController/tiger_models/'  # This path refers to a path inside the controller docker container
  replay_buffer_max_capacity: 1000
  agent_memory_size: 2000
  learning_rate: 1e-3
  repulsive_weight: 1
  attractive_weight: 1
  kernel_regressor_heads: 2
  clustering_loss_backprop: True
  init_epsilon_egreedy: 1.0
  greedy_min: 0.01
  greedy_decay: 0.999
  agent_discount_rate: 0.99
  epistemic_agency: true # activates the management agent, false to only pretrain the inference modules.
  save_models: false # overwritte models on disk.

honeypots:
  - victim-0:
      pattern: 'doorlock'
      destination: 'victim-1'
  - victim-1:
      pattern: 'echo'
      destination: 'victim-2'
  - victim-2:
      pattern: 'hue'
      destination: 'victim-0'

attackers:
  - attacker-1:
      pattern: 'cc_heartbeat'
      destination: 'victim-0'
  - attacker-2:
      pattern: 'generic_ddos'
      destination: 'victim-1'
  - attacker-3:
      pattern: 'h_scan'
      destination: 'victim-2'
  - attacker-4:
      pattern: 'hakai'
      destination: 'victim-0'
  - attacker-5:
      pattern: 'torii'
      destination: 'victim-1'
  - attacker-6:
      pattern: 'mirai'
      destination: 'victim-2'
  - attacker-7:
      pattern: 'gafgyt'
      destination: 'victim-0'
  - attacker-8:
      pattern: 'hajime'
      destination: 'victim-1'
  - attacker-9:
      pattern: 'okiru'
      destination: 'victim-2'
  - attacker-10:
      pattern: 'muhstik'
      destination: 'victim-0'


rewards:
    - echo: 0.02
    - hakai: -0.20
    - mirai: -0.40
    - hajime: -0.26
    - doorlock: 0.01
    - gafgyt: -0.5
    - muhstik: -0.6
    - h_scan: -0.7
    - okiru: -0.8
    - generic_ddos: -0.9
    - torii: -0.51
    - cc_heartbeat: -0.61
    - hue: 0.05


knowledge:

    bening_patterns: 
        - echo
        - doorlock
        - hue

    malicious_patterns:
        - hakai
        - mirai
        - hajime
        - gafgyt
        - muhstik
        - h_scan
        - okiru
        - generic_ddos
        - torii
        - cc_heartbeat

    Knowns:
        - hue
        - hakai
        - torii

    G1s:
        - okiru
        - cc_heartbeat
        - generic_ddos
        

    G2s:
        - mirai
        - gafgyt
        - hajime
        - h_scan
        - muhstik
        - doorlock
        - echo


